[package]
name = "DexlynCoin"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
dexlyn_coin = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
dexlyn_coin_owner = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
dexlyn_coin_minter = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"


[dependencies]
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", rev = "dev", subdir = "aptos-move/framework/supra-framework" }

#Enable the following line if you want to use the local version of SupraFramework
#SupraFramework = { local = '../../supra-dev-block/aptos-move/framework/supra-framework' }

