[package]
name = 'DexlynTokenomics'
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
dexlyn_tokenomics = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
owner = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
vesting_admin = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
emission_admin = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
voter_admin = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
voter_governance = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
voter_minter = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
fee_treasury = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"

voting_escrow_admin = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
voting_escrow_voter = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
admin = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"
emergency_return = "0x3e12a0ec8c197d2adf43dcb9ebd3b25777e79b2e6fa8e8c9fbe38a8cdfee041c"

[dependencies]
# Git version (disabled for testing)
# SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", rev = "dev", subdir = "aptos-move/framework/supra-framework" }
# AptosTokenObjects = { git = "https://github.com/Entropy-Foundation/aptos-core.git", rev = "dev", subdir = "aptos-move/framework/aptos-token-objects" }

# Local version with test support (enabled)
SupraFramework = { local = '../aptos-core/aptos-move/framework/supra-framework' }
AptosTokenObjects = { local = '../aptos-core/aptos-move/framework/aptos-token-objects' }
dexlyn_swap = { local = "/Users/huang/Documents/web3-audit/2025/hai/dex_contracts" }
DexlynClmm = { git = 'https://github.com/DexlynLabs/CLMM_Dex.git', subdir = 'DexlynClmm', rev = 'master' }
DexlynCoin = { local = './dexlyn_coin' }
dexlyn-perp-trade = { local = './dexlyn_perp_dex' }

#Enable the following line if you want to use the local version of SupraFramework
# SupraFramework = { local = '../aptos-core/aptos-move/framework/supra-framework' }
# AptosTokenObjects = { local = '../aptos-core/aptos-move/framework/aptos-token-objects' }
#dexlyn_swap = { local = '../dexlyn_swap' }s
#DexlynClmm = { local = '../dexlyn_swap_v2/CetusCompile/CetusClmm' }


#[dependencies.SupraMoveUtils]
#local = '../supra-move-utils'